Vagrant.configure(2) do |config|

  config.vm.define "test01" do |node|
    node.vm.box = "jeqo/azul-zulu-8-centos7"

    node.vm.provision "ansible" do |ansible|
      ansible.playbook = "test.yml"
      ansible.galaxy_role_file = "roles.yml"
    end
  end

  config.vm.define "test02" do |node|
    node.vm.box = "jeqo/azul-zulu-8-ubuntu14"

    node.vm.provision "ansible" do |ansible|
      ansible.playbook = "test.yml"
      ansible.galaxy_role_file = "roles.yml"
    end
  end
end
